<?php
if(empty($_COOKIE[LANG])){
    setcookie('LANG',"CH",time()+3600*24*7,'/general/customer_relationship/');  //默认设置为中文
}
global $LG_CUSTOMER_DATA;
$LG_CUSTOMER_DATA=array();
$LG_CUSTOMER_DATA['客户信息列表'] = array("CH"=>"客户信息列表","EN"=>"Client Information List");
$LG_CUSTOMER_DATA['客户信息登记变更'] = array("CH"=>"客户信息登记变更","EN"=>"Client Information Registration Change");
$LG_CUSTOMER_DATA['客户信息共享'] = array("CH"=>"客户信息共享","EN"=>"Client Information Sharing");
$LG_CUSTOMER_DATA['客户信息修改'] = array("CH"=>"客户信息修改","EN"=>"Client Information Modification");
$LG_CUSTOMER_DATA['客户信息登记表'] = array("CH"=>"客户信息登记表","EN"=>"Client Information Registration");
$LG_CUSTOMER_DATA['登记单号'] = array("CH"=>"登记单号","EN"=>"Contract No.");
$LG_CUSTOMER_DATA['请输入登记单号'] = array("CH"=>"请输入登记单号","EN"=>"Please Enter the Contract No.");
$LG_CUSTOMER_DATA['客户名称'] = array("CH"=>"客户名称","EN"=>"Client Name");
$LG_CUSTOMER_DATA['请输入客户名称'] = array("CH"=>"请输入客户名称","EN"=>"Please Enter the Client Name");
$LG_CUSTOMER_DATA['查询'] = array("CH"=>"查询","EN"=>"Query");
$LG_CUSTOMER_DATA['新建'] = array("CH"=>"新建","EN"=>"Add");
$LG_CUSTOMER_DATA['申请'] = array("CH"=>"申请","EN"=>"apply");
$LG_CUSTOMER_DATA['变更'] = array("CH"=>"变更","EN"=>"Change");
$LG_CUSTOMER_DATA['共享'] = array("CH"=>"共享","EN"=>"Share");
$LG_CUSTOMER_DATA['帮助'] = array("CH"=>"帮助","EN"=>"Help");
$LG_CUSTOMER_DATA['选择'] = array("CH"=>"选择","EN"=>"Select");
$LG_CUSTOMER_DATA['序号'] = array("CH"=>"序号","EN"=>"Serial No.");
$LG_CUSTOMER_DATA['大洲'] = array("CH"=>"大洲","EN"=>"Continent");
$LG_CUSTOMER_DATA['国家'] = array("CH"=>"国家","EN"=>"Country");
$LG_CUSTOMER_DATA['制单人'] = array("CH"=>"制单人","EN"=>"Prepared by");
$LG_CUSTOMER_DATA['制单时间'] = array("CH"=>"制单时间","EN"=>"Date of Compiling");
$LG_CUSTOMER_DATA['办理状态'] = array("CH"=>"办理状态","EN"=>"Processing Status");
$LG_CUSTOMER_DATA['待提交'] = array("CH"=>"待提交","EN"=>"To be Submitted");
$LG_CUSTOMER_DATA['审核中'] = array("CH"=>"审核中","EN"=>"Checking");
$LG_CUSTOMER_DATA['备案中'] = array("CH"=>"备案中","EN"=>"Filing");
$LG_CUSTOMER_DATA['已审核'] = array("CH"=>"已审核","EN"=>"Checked");
$LG_CUSTOMER_DATA['退回'] = array("CH"=>"退回","EN"=>"Return");
$LG_CUSTOMER_DATA['操作'] = array("CH"=>"操作","EN"=>"Operate");
$LG_CUSTOMER_DATA['查阅'] = array("CH"=>"查阅","EN"=>"Detail");
$LG_CUSTOMER_DATA['查看进度'] = array("CH"=>"查看进度","EN"=>"View Progress");
$LG_CUSTOMER_DATA['退回'] = array("CH"=>"退回","EN"=>"Return");
$LG_CUSTOMER_DATA['待办'] = array("CH"=>"待办","EN"=>"Processing");
$LG_CUSTOMER_DATA['办理完成'] = array("CH"=>"办理完成","EN"=>"Processing completed");
$LG_CUSTOMER_DATA['结束'] = array("CH"=>"结束","EN"=>"End");
$LG_CUSTOMER_DATA['跟进'] = array("CH"=>"跟进","EN"=>"Follow up");
$LG_CUSTOMER_DATA['修改'] = array("CH"=>"修改","EN"=>"Edit");
$LG_CUSTOMER_DATA['删除'] = array("CH"=>"删除","EN"=>"Delete");
$LG_CUSTOMER_DATA['暂无数据'] = array("CH"=>"暂无数据","EN"=>"No Data");
$LG_CUSTOMER_DATA['提醒'] = array("CH"=>"提醒","EN"=>"Remind");
$LG_CUSTOMER_DATA['您确认新建银河耐吉客户信息登记表吗？'] = array("CH"=>"您确认新建银河耐吉客户信息登记表吗？","EN"=>"Do you confirm the new Inhenergy Client Information Registration Form?");
$LG_CUSTOMER_DATA['确认'] = array("CH"=>"确认","EN"=>"Confirm");
$LG_CUSTOMER_DATA['取消'] = array("CH"=>"取消","EN"=>"Cancel");
$LG_CUSTOMER_DATA['提交'] = array("CH"=>"提交","EN"=>"Submit");
$LG_CUSTOMER_DATA['保存'] = array("CH"=>"保存","EN"=>"Save");
$LG_CUSTOMER_DATA['关闭'] = array("CH"=>"关闭","EN"=>"Exit");
$LG_CUSTOMER_DATA['简称'] = array("CH"=>"简称","EN"=>"Abbreviation");
$LG_CUSTOMER_DATA['请输入简称'] = array("CH"=>"请输入简称","EN"=>"Please Enter the Abbreviation");
$LG_CUSTOMER_DATA['请选择'] = array("CH"=>"请选择","EN"=>"Please Select");
$LG_CUSTOMER_DATA['网址'] = array("CH"=>"网址","EN"=>"Website");
$LG_CUSTOMER_DATA['最多150个字符'] = array("CH"=>"最多150个字符","EN"=>"A Maximum of 150 Characters");
$LG_CUSTOMER_DATA['地址'] = array("CH"=>"地址","EN"=>"Address");
$LG_CUSTOMER_DATA['请输入客户地址'] = array("CH"=>"请输入客户地址","EN"=>"Please Enter the Client Address");
$LG_CUSTOMER_DATA['类型'] = array("CH"=>"类型","EN"=>"Type");
$LG_CUSTOMER_DATA['客户类型'] = array("CH"=>"客户类型","EN"=>"Client Type");
$LG_CUSTOMER_DATA['经销商'] = array("CH"=>"经销商","EN"=>"Distributors");
$LG_CUSTOMER_DATA['安装商'] = array("CH"=>"安装商","EN"=>"Installers");
$LG_CUSTOMER_DATA['贸易商'] = array("CH"=>"贸易商","EN"=>"Traders");
$LG_CUSTOMER_DATA['代理商'] = array("CH"=>"代理商","EN"=>"Agents");
$LG_CUSTOMER_DATA['集成商'] = array("CH"=>"集成商","EN"=>"Integrators");
$LG_CUSTOMER_DATA['资源共享合作商'] = array("CH"=>"资源共享合作商","EN"=>"Resource Sharing Partners");
$LG_CUSTOMER_DATA['星级'] = array("CH"=>"星级","EN"=>"Rank");
$LG_CUSTOMER_DATA['一星级'] = array("CH"=>"一星级","EN"=>"One-Star");
$LG_CUSTOMER_DATA['二星级'] = array("CH"=>"二星级","EN"=>"Two-Star");
$LG_CUSTOMER_DATA['三星级'] = array("CH"=>"三星级","EN"=>"Three-Star");
$LG_CUSTOMER_DATA['四星级'] = array("CH"=>"四星级","EN"=>"Four-Star");
$LG_CUSTOMER_DATA['五星级'] = array("CH"=>"五星级","EN"=>"Five-Star");
$LG_CUSTOMER_DATA['不符合'] = array("CH"=>"不符合","EN"=>"Inconformity");
$LG_CUSTOMER_DATA['星级图标'] = array("CH"=>"星级图标","EN"=>"StarIcon");
$LG_CUSTOMER_DATA['客户概述'] = array("CH"=>"客户概述","EN"=>"Client Introduction");
$LG_CUSTOMER_DATA['概述'] = array("CH"=>"概述","EN"=>"Client Introduction");
$LG_CUSTOMER_DATA['请输入客户概述'] = array("CH"=>"请输入客户概述","EN"=>"Please Enter the Client Introduction");
$LG_CUSTOMER_DATA['客户关注'] = array("CH"=>"客户关注","EN"=>"Client Focus");
$LG_CUSTOMER_DATA['请输入客户关注点'] = array("CH"=>"请输入客户关注点","EN"=>"Please Enter the Client Focus");
$LG_CUSTOMER_DATA['联系人'] = array("CH"=>"联系人","EN"=>"Contacts");
$LG_CUSTOMER_DATA['姓名'] = array("CH"=>"姓名","EN"=>"Name");
$LG_CUSTOMER_DATA['电话1'] = array("CH"=>"电话1","EN"=>"Tel No.1");
$LG_CUSTOMER_DATA['电话2'] = array("CH"=>"电话2","EN"=>"Tel No.2");
$LG_CUSTOMER_DATA['邮箱'] = array("CH"=>"邮箱","EN"=>"E-mail");
$LG_CUSTOMER_DATA['地址'] = array("CH"=>"地址","EN"=>"Address");
$LG_CUSTOMER_DATA['备注'] = array("CH"=>"备注","EN"=>"Notes");
$LG_CUSTOMER_DATA['添加'] = array("CH"=>"添加","EN"=>"Add");
$LG_CUSTOMER_DATA['客户关联公司'] = array("CH"=>"客户关联公司","EN"=>"Client Related Company");
$LG_CUSTOMER_DATA['合同相对方'] = array("CH"=>"合同相对方","EN"=>"Contract Party");
$LG_CUSTOMER_DATA['联系人姓名'] = array("CH"=>"联系人姓名","EN"=>"Contacts");
$LG_CUSTOMER_DATA['电话'] = array("CH"=>"电话","EN"=>"Tel No.");
$LG_CUSTOMER_DATA['所属部门'] = array("CH"=>"所属部门","EN"=>"Department");
$LG_CUSTOMER_DATA['登记人'] = array("CH"=>"登记人","EN"=>"Registrant");
$LG_CUSTOMER_DATA['登记时间'] = array("CH"=>"登记时间","EN"=>"Registration Time");
$LG_CUSTOMER_DATA['共享业务人员'] = array("CH"=>"共享业务人员","EN"=>"Business Sharing Personnel");
$LG_CUSTOMER_DATA['跟进记录'] = array("CH"=>"跟进记录","EN"=>"Follow-up Record");
$LG_CUSTOMER_DATA['跟进人员'] = array("CH"=>"跟进人员","EN"=>"Follow-up Personnel");
$LG_CUSTOMER_DATA['跟进日期'] = array("CH"=>"跟进日期","EN"=>"Follow-up Date");
$LG_CUSTOMER_DATA['创建时间'] = array("CH"=>"创建时间","EN"=>"Creation Time");
$LG_CUSTOMER_DATA['接洽方式'] = array("CH"=>"接洽方式","EN"=>"Contact mode");
$LG_CUSTOMER_DATA['目前供应商'] = array("CH"=>"目前供应商","EN"=>"Current Suppliers");
$LG_CUSTOMER_DATA['当前供应商'] = array("CH"=>"当前供应商","EN"=>"Current Suppliers");
$LG_CUSTOMER_DATA['是否有意向采购产品'] = array("CH"=>"是否有意向采购产品","EN"=>"An Intention to Purchase Our Products or Not");
$LG_CUSTOMER_DATA['是否有采购意向'] = array("CH"=>"是否有采购意向","EN"=>"An Intention to Purchase Our Products or Not");
$LG_CUSTOMER_DATA['是'] = array("CH"=>"是","EN"=>"Yes");
$LG_CUSTOMER_DATA['否'] = array("CH"=>"否","EN"=>"No");
$LG_CUSTOMER_DATA['总数量'] = array("CH"=>"总数量","EN"=>"Total Quantity");
$LG_CUSTOMER_DATA['需求'] = array("CH"=>"需&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;求","EN"=>"Demand");
$LG_CUSTOMER_DATA['附件'] = array("CH"=>"附&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;件","EN"=>"Attachment");
$LG_CUSTOMER_DATA['商谈事项'] = array("CH"=>"商谈事项","EN"=>"Negotiate Matters");
$LG_CUSTOMER_DATA['新增跟进'] = array("CH"=>"新增跟进","EN"=>"New follow-up");
$LG_CUSTOMER_DATA['微信'] = array("CH"=>"微信","EN"=>"WeChat");
$LG_CUSTOMER_DATA['邮箱'] = array("CH"=>"邮箱","EN"=>"E-mail");
$LG_CUSTOMER_DATA['电话'] = array("CH"=>"电话","EN"=>"Tel No.");
$LG_CUSTOMER_DATA['拜访'] = array("CH"=>"拜访","EN"=>"Visiting");
$LG_CUSTOMER_DATA['其他'] = array("CH"=>"其他","EN"=>"Else");
$LG_CUSTOMER_DATA['流程进度'] = array("CH"=>"流程进度","EN"=>"Process Schedule");
$LG_CUSTOMER_DATA['流程步骤'] = array("CH"=>"流程步骤","EN"=>"Process Step");
$LG_CUSTOMER_DATA['状态'] = array("CH"=>"状态","EN"=>"Status");
$LG_CUSTOMER_DATA['办理人'] = array("CH"=>"办理人","EN"=>"Handler");
$LG_CUSTOMER_DATA['办理时间'] = array("CH"=>"办理时间","EN"=>"Handling Time");
$LG_CUSTOMER_DATA['交办人'] = array("CH"=>"交办人","EN"=>"Assigner");
$LG_CUSTOMER_DATA['交办时间'] = array("CH"=>"交办时间","EN"=>"Assigning time");
$LG_CUSTOMER_DATA['公司'] = array("CH"=>"公司","EN"=>"Company");
$LG_CUSTOMER_DATA['跟进距今天数'] = array("CH"=>"跟进距今天数","EN"=>"Days not followed up");
$LG_CUSTOMER_DATA['大于多少天'] = array("CH"=>"大于多少天","EN"=>"More than how many days");
$LG_CUSTOMER_DATA['客户来源'] = array("CH"=>"客户来源","EN"=>"Customer Source");
$LG_CUSTOMER_DATA['主动开发'] = array("CH"=>"主动开发","EN"=>"Active development");
$LG_CUSTOMER_DATA['线上询盘'] = array("CH"=>"线上询盘","EN"=>"Online inquiry");
$LG_CUSTOMER_DATA['展会获取'] = array("CH"=>"展会获取","EN"=>"Exhibition acquisition");
$LG_CUSTOMER_DATA['第三方介绍'] = array("CH"=>"第三方介绍","EN"=>"Third Party Introduction");
$LG_CUSTOMER_DATA['职位'] = array("CH"=>"职位","EN"=>"Position");
$LG_CUSTOMER_DATA['变更说明'] = array("CH"=>"变更说明","EN"=>"Change Description");
$LG_CUSTOMER_DATA['是否有效'] = array("CH"=>"是否有效","EN"=>"Valid or not");
$LG_CUSTOMER_DATA['是否成交订单'] = array("CH"=>"是否成交订单","EN"=>"Transaction order or not");
$LG_CUSTOMER_DATA['办理'] = array("CH"=>"办理","EN"=>"Handling");
$LG_CUSTOMER_DATA['客户跟踪'] = array("CH"=>"客户跟踪","EN"=>"Customer Follower");
$LG_CUSTOMER_DATA['打印'] = array("CH"=>"打印","EN"=>"Print");
$LG_CUSTOMER_DATA['有采购意向，总数量必须大于0'] = array("CH"=>"有采购意向，总数量必须大于0","EN"=>"Intention to purchase, total quantity must be greater than 0");
$LG_CUSTOMER_DATA['成功'] = array("CH"=>"成功","EN"=>"Success");
$LG_CUSTOMER_DATA['失败'] = array("CH"=>"失败","EN"=>"fail");
$LG_CUSTOMER_DATA['联系人不能为空！'] = array("CH"=>"联系人不能为空！","EN"=>"Contact person cannot be empty!");
$LG_CUSTOMER_DATA['联系人姓名不能为空！'] = array("CH"=>"联系人姓名不能为空！","EN"=>"Contact name cannot be empty!");
$LG_CUSTOMER_DATA['电话或者邮箱不能为空！'] = array("CH"=>"电话或者邮箱不能为空！","EN"=>"Phone or email cannot be empty!");
$LG_CUSTOMER_DATA['填表说明'] = array("CH"=>"填表说明","EN"=>"Important note");
$LG_CUSTOMER_DATA['填表说明1'] = array("CH"=>"重要提示：合同评审中“合同相对方”（合同签订方和付款方）若和“客户名称”不一样，则必须在此客户信息登记表中，登记“合同相对方”信息。","EN"=>'In contract review, if the "contract counterparty" (contract signing party and payer) is different from the "customer name", the "contract counterparty" information must be registered in this customer information registration form.');
$LG_CUSTOMER_DATA['填表说明2'] = array("CH"=>"重要提示：客户名称必须要全名，将引用到合同评审页面，且不允许更改。","EN"=>"The customer name must be in full and will be referenced on the contract review page, and cannot be changed.");
$LG_CUSTOMER_DATA['跟进距今天数只能填写数字'] = array("CH"=>"跟进距今天数只能填写数字","EN"=>"Follow up to today can only be filled in numbers");
//import
$LG_CUSTOMER_DATA['导入'] =array("CH"=>"导入","EN"=>"Import");
$LG_CUSTOMER_DATA['客户信息导入'] =array("CH"=>"客户信息导入","EN"=>"Customer information import");
$LG_CUSTOMER_DATA['只能导入Excel文件'] =array("CH"=>"只能导入Excel文件","EN"=>"Only Excel files can be imported");
$LG_CUSTOMER_DATA['文件已导入，请勿重复导入'] =array("CH"=>"文件已导入，请勿重复导入","EN"=>"The file has been imported, please do not import it again");
$LG_CUSTOMER_DATA['创建时间不能为空'] =array("CH"=>"创建时间不能为空","EN"=>"Creation time cannot be empty.");
$LG_CUSTOMER_DATA['客户信息红色栏位必填项不能为空'] =array("CH"=>"客户信息红色栏位必填项不能为空","EN"=>"The mandatory red field of customer information cannot be blank.");
$LG_CUSTOMER_DATA['简称已存在'] =array("CH"=>"简称已存在","EN"=>"Abbreviation already exists.");
$LG_CUSTOMER_DATA['客户已存在'] =array("CH"=>"客户已存在","EN"=>"Customer already exists.");
$LG_CUSTOMER_DATA['联系人姓名不能为空'] =array("CH"=>"联系人姓名不能为空","EN"=>"Contact name cannot be empty.");
$LG_CUSTOMER_DATA['存在跟进记录时，跟进记录信息红色栏位必填项不能为空'] =array("CH"=>"存在跟进记录时，跟进记录信息红色栏位必填项不能为空","EN"=>"When there are follow-up records, the mandatory red field of follow-up record information cannot be blank.");
$LG_CUSTOMER_DATA['存在合同相对方时，相对方名称不能为空'] =array("CH"=>"存在合同相对方时，相对方名称不能为空","EN"=>"When there is a contract counterparty, the counterparty name cannot be empty.");
$LG_CUSTOMER_DATA['有采购意向，总数量必须大于0'] =array("CH"=>"有采购意向，总数量必须大于0","EN"=>"Intention to purchase, total quantity must be greater than 0.");
$LG_CUSTOMER_DATA['数据导入失败'] =array("CH"=>"数据导入失败","EN"=>"Data import failed");
$LG_CUSTOMER_DATA['导入客户数据失败'] =array("CH"=>"导入数据","EN"=>"Failed to import customer data");
$LG_CUSTOMER_DATA['修改客户数据失败'] =array("CH"=>"修改客户数据失败","EN"=>"Failed to modify customer data");
$LG_CUSTOMER_DATA['修改联系人失败'] =array("CH"=>"修改联系人失败","EN"=>"Failed to modify contact");
$LG_CUSTOMER_DATA['导入联系人失败'] =array("CH"=>"导入联系人失败","EN"=>"Failed to import contacts");
$LG_CUSTOMER_DATA['修改合同相对方失败'] =array("CH"=>"修改合同相对方失败","EN"=>"Failed to modify the opposite party of the contract");
$LG_CUSTOMER_DATA['导入合同相对方失败'] =array("CH"=>"导入合同相对方失败","EN"=>"Failed to import contract counterpart");
$LG_CUSTOMER_DATA['导入跟进记录失败'] =array("CH"=>"导入跟进记录失败","EN"=>"Import follow-up record failed");
$LG_CUSTOMER_DATA['更新客户版本信息失败'] =array("CH"=>"更新客户版本信息失败","EN"=>"Failed to update customer version information");
$LG_CUSTOMER_DATA['更新导入数据状态失败'] =array("CH"=>"更新导入数据状态失败","EN"=>"Failed to update import data status");
$LG_CUSTOMER_DATA['导入失败行：'] =array("CH"=>"导入失败行：","EN"=>"Import failed rows:");
$LG_CUSTOMER_DATA['原因：'] =array("CH"=>"原因：","EN"=>"Reason:");
$LG_CUSTOMER_DATA['共导入数据：'] =array("CH"=>"共导入数据：","EN"=>"Import data together:");
$LG_CUSTOMER_DATA['返回'] =array("CH"=>"返回","EN"=>"Back");
$LG_CUSTOMER_DATA['下载导入模板'] =array("CH"=>"下载导入模板","EN"=>"Download import template");
$LG_CUSTOMER_DATA['导入模板'] =array("CH"=>"导入模板：","EN"=>"Import Template:");
$LG_CUSTOMER_DATA['选择导入文件'] =array("CH"=>"选择导入文件：","EN"=>"Select Import File:");
$LG_CUSTOMER_DATA['导入注意'] =array("CH"=>"注意：请下载导入模板后填写数据后导入，导入模板请勿新增或修改任何的格式,模板中红色栏位为必填项","EN"=>"Important note:Please download the import template and fill in the data before importing. Please do not add or modify any formatting in the import template");
$LG_CUSTOMER_DATA['请选择要导入的文件'] =array("CH"=>"请选择要导入的文件","EN"=>"Please select the file to import");
$LG_CUSTOMER_DATA['联系人电话1'] =array("CH"=>"联系人电话1","EN"=>"Contacts Tel 1");
$LG_CUSTOMER_DATA['联系人电话2'] =array("CH"=>"联系人电话2","EN"=>"Contacts Tel 2");
$LG_CUSTOMER_DATA['联系人邮箱'] =array("CH"=>"联系人邮箱","EN"=>"Contacts E-mail");
$LG_CUSTOMER_DATA['联系人地址'] =array("CH"=>"联系人地址","EN"=>"Contacts Address");
$LG_CUSTOMER_DATA['联系人备注'] =array("CH"=>"联系人备注","EN"=>"Contacts Notes");
$LG_CUSTOMER_DATA['联系人职位'] =array("CH"=>"联系人职位","EN"=>"Contacts Position");
$LG_CUSTOMER_DATA['相对方名称'] =array("CH"=>"相对方名称","EN"=>"Contract Party");
$LG_CUSTOMER_DATA['相对方简称'] =array("CH"=>"相对方简称","EN"=>"Contract Party Abbreviation");
$LG_CUSTOMER_DATA['相对方国家'] =array("CH"=>"相对方国家","EN"=>"Contract Party Country");
$LG_CUSTOMER_DATA['相对方地址'] =array("CH"=>"相对方地址","EN"=>"Contract Party Address");
$LG_CUSTOMER_DATA['相对方联系人'] =array("CH"=>"相对方联系人","EN"=>"Contract Party Contacts");
$LG_CUSTOMER_DATA['相对方电话'] =array("CH"=>"相对方电话","EN"=>"Contract Party Tel No.");
?>