/*
Navicat MySQL Data Transfer

Source Server         : localhost_3336
Source Server Version : 50525
Source Host           : localhost:3336
Source Database       : TD_OA

Target Server Type    : MYSQL
Target Server Version : 50525
File Encoding         : 65001

Date: 2020-10-07 10:30:37
*/

SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- Table structure for sys_function
-- ----------------------------
DROP TABLE IF EXISTS `sys_function`;
CREATE TABLE `sys_function` (
  `FUNC_ID` int(11) NOT NULL DEFAULT '0' COMMENT '菜单ID',
  `MENU_ID` varchar(10) NOT NULL DEFAULT '0' COMMENT '子菜单项代码',
  `FUNC_NAME` varchar(100) NOT NULL DEFAULT '' COMMENT '子菜单名称',
  `FUNC_CODE` varchar(300) NOT NULL COMMENT '子菜单模块路径',
  `FUNC_EXT` varchar(600) NOT NULL COMMENT '国际版多语言菜单名称',
  PRIMARY KEY (`FUNC_ID`),
  KEY `MENU_ID` (`MENU_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=gbk COMMENT='系统菜单表';

-- ----------------------------
-- Records of sys_function
-- ----------------------------
INSERT INTO `sys_function` VALUES ('1', '0101', '电子邮件', 'email', '');
INSERT INTO `sys_function` VALUES ('2', '4510', '管理中心门户', 'management_center/portal', '');
INSERT INTO `sys_function` VALUES ('3', '0102', '消息管理', 'sms', '');
INSERT INTO `sys_function` VALUES ('4', '0116', '公告通知', 'notify/show', '');
INSERT INTO `sys_function` VALUES ('5', '1020', '我的工作', 'workflow/list', '');
INSERT INTO `sys_function` VALUES ('6', 'z01220', '手机短信设置', 'system/mobile_sms', '');
INSERT INTO `sys_function` VALUES ('7', '0120', '个人考勤', 'attendance/personal', '');
INSERT INTO `sys_function` VALUES ('8', '0124', '日程安排', 'calendar', '');
INSERT INTO `sys_function` VALUES ('9', '0128', '工作日志', 'diary/show', '');
INSERT INTO `sys_function` VALUES ('10', '0132', '通讯簿', 'address/private', '');
INSERT INTO `sys_function` VALUES ('11', '0140', '控制面板', 'person_info', '');
INSERT INTO `sys_function` VALUES ('12', '4515', '管理中心设置', '@management_center', '');
INSERT INTO `sys_function` VALUES ('13', '4560', 'BI设计中心', '@bi_design', '');
INSERT INTO `sys_function` VALUES ('14', '456020', '智能报表BI设计', 'bi_design/reportshop', '');
INSERT INTO `sys_function` VALUES ('15', '3001', '公共文件柜', 'knowledge_management', '');
INSERT INTO `sys_function` VALUES ('16', '0136', '个人文件柜', 'file_folder/index2.php', '');
INSERT INTO `sys_function` VALUES ('17', '206002', '单位信息查询', 'info/unit', '');
INSERT INTO `sys_function` VALUES ('18', '206004', '部门信息查询', 'info/dept', '');
INSERT INTO `sys_function` VALUES ('19', '206006', '用户信息查询', 'info/user', '');
INSERT INTO `sys_function` VALUES ('21', 'y00402', '电话区号查询', 'info/tel_no', '');
INSERT INTO `sys_function` VALUES ('22', 'y00404', '邮政编码查询', 'info/post_no', '');
INSERT INTO `sys_function` VALUES ('24', '2006', '公告通知管理', 'notify/manage', '');
INSERT INTO `sys_function` VALUES ('26', '5007', '考勤管理', '@attendance/manage', '');
INSERT INTO `sys_function` VALUES ('27', '5022', '人事管理', '@hr', '');
INSERT INTO `sys_function` VALUES ('28', '501107', '财务工资录入', 'hr/salary/submit', '');
INSERT INTO `sys_function` VALUES ('29', '501105', '工资流程管理', 'hr/salary/manage', '');
INSERT INTO `sys_function` VALUES ('30', 'z00402', '单位管理', 'system/unit', '');
INSERT INTO `sys_function` VALUES ('31', 'z00406', '部门管理', 'system/dept', '');
INSERT INTO `sys_function` VALUES ('32', 'z00410', '角色与权限管理', 'system/user_priv', '');
INSERT INTO `sys_function` VALUES ('33', 'z00408', '用户管理', 'system/user', '');
INSERT INTO `sys_function` VALUES ('34', 'z01230', '讨论区设置', 'system/bbs', '');
INSERT INTO `sys_function` VALUES ('36', 'z01010', '公共文件柜设置', 'system/file_folder', '');
INSERT INTO `sys_function` VALUES ('37', 'z00610', '设计表单', 'system/workflow/flow_form', '');
INSERT INTO `sys_function` VALUES ('38', 'z099', '系统信息', 'system/reg_view', '');
INSERT INTO `sys_function` VALUES ('39', '501501', '考勤设置', 'hr/setting/attendance', '');
INSERT INTO `sys_function` VALUES ('40', '456030', '工作流BI设计', 'bi_design/workflow', '');
INSERT INTO `sys_function` VALUES ('41', '456040', 'OA业务BI设计', 'bi_design/oa', '');
INSERT INTO `sys_function` VALUES ('42', '0104', '手机短信', 'mobile_sms', '');
INSERT INTO `sys_function` VALUES ('43', '2060', '组织机构信息', '@unit', '');
INSERT INTO `sys_function` VALUES ('44', '456050', '外部业务BI设计', 'bi_design/external', '');
INSERT INTO `sys_function` VALUES ('46', 'y004', '实用信息', '@infofind', '');
INSERT INTO `sys_function` VALUES ('51', '2036', '图书管理', '@book', '');
INSERT INTO `sys_function` VALUES ('52', '203612', '图书类别定义', 'book/type', '');
INSERT INTO `sys_function` VALUES ('53', '203604', '图书录入', 'book/manage', '');
INSERT INTO `sys_function` VALUES ('54', '203606', '图书查询', 'book/query', '');
INSERT INTO `sys_function` VALUES ('55', '5011', '薪酬管理', '@hr', '');
INSERT INTO `sys_function` VALUES ('56', 'z004', '组织机构设置', '@system', '');
INSERT INTO `sys_function` VALUES ('57', 'z008', '行政办公设置', '@system', '');
INSERT INTO `sys_function` VALUES ('58', 'z012', '信息交流设置', '@system', '');
INSERT INTO `sys_function` VALUES ('59', '4005', '我的门户', 'portal', '');
INSERT INTO `sys_function` VALUES ('60', '502201', '人事档案', 'hr/manage/staff_info', '');
INSERT INTO `sys_function` VALUES ('61', '502202', '档案查询', 'hr/manage/query', '');
INSERT INTO `sys_function` VALUES ('62', 'b002', '讨论区', 'bbs', '');
INSERT INTO `sys_function` VALUES ('63', 'b003', '论坛', 'bbs2', '');
INSERT INTO `sys_function` VALUES ('64', '4085', '门户模版管理', 'system/portal/template', '');
INSERT INTO `sys_function` VALUES ('65', '9010', '我的项目', 'project/portal', '');
INSERT INTO `sys_function` VALUES ('66', '451510', '分类设置', 'management_center/setting/class', '');
INSERT INTO `sys_function` VALUES ('67', '451520', '权限设置', 'management_center/setting/priv', '');
INSERT INTO `sys_function` VALUES ('68', '451505', '全局设置', 'management_center/setting/global', '');
INSERT INTO `sys_function` VALUES ('76', '3010', '网络硬盘', 'netdisk', '');
INSERT INTO `sys_function` VALUES ('77', 'z01020', '网络硬盘设置', 'system/netdisk', '');
INSERT INTO `sys_function` VALUES ('78', 'z030', '界面设置', 'system/interface', '');
INSERT INTO `sys_function` VALUES ('80', '2016', '日程安排查询', 'calendar/info', '');
INSERT INTO `sys_function` VALUES ('84', 'z055', '数据库管理', 'system/database', '');
INSERT INTO `sys_function` VALUES ('85', '2050', '会议申请与安排', '@meeting', '');
INSERT INTO `sys_function` VALUES ('86', '205001', '会议申请', 'meeting/apply', '');
INSERT INTO `sys_function` VALUES ('87', '205002', '会议查询', 'meeting/query', '');
INSERT INTO `sys_function` VALUES ('88', '205003', '会议管理', 'meeting/manage', '');
INSERT INTO `sys_function` VALUES ('89', '205004', '会议室设置', 'meeting/meeting_room', '');
INSERT INTO `sys_function` VALUES ('90', '2055', '车辆申请与安排', '@vehicle', '');
INSERT INTO `sys_function` VALUES ('91', '205503', '车辆使用申请', 'vehicle', '');
INSERT INTO `sys_function` VALUES ('92', '205506', '车辆使用查询', 'vehicle/query', '');
INSERT INTO `sys_function` VALUES ('93', '205508', '车辆使用管理', 'vehicle/checkup', '');
INSERT INTO `sys_function` VALUES ('94', '205510', '车辆维护管理', 'vehicle/maintenance', '');
INSERT INTO `sys_function` VALUES ('95', '205512', '车辆信息管理', 'vehicle/manage', '');
INSERT INTO `sys_function` VALUES ('96', '2020', '工作计划', '@work_plan', '');
INSERT INTO `sys_function` VALUES ('97', '202003', '工作计划查询', 'work_plan/show', '');
INSERT INTO `sys_function` VALUES ('98', '202006', '工作计划管理', 'work_plan/manage', '');
INSERT INTO `sys_function` VALUES ('99', 'z060', '系统日志管理', 'system/log', '');
INSERT INTO `sys_function` VALUES ('100', 'z065', '系统资源管理', 'system/res_manage', '');
INSERT INTO `sys_function` VALUES ('101', 'z075', '系统访问控制', 'system/access_control', '');
INSERT INTO `sys_function` VALUES ('103', 'z00810', '公共网址设置', 'system/url', '');
INSERT INTO `sys_function` VALUES ('104', 'z040', '菜单设置', 'system/menu', '');
INSERT INTO `sys_function` VALUES ('105', '2013', '新闻管理', 'news/manage', '');
INSERT INTO `sys_function` VALUES ('107', 'z00815', '公共通讯簿设置', 'system/address', '');
INSERT INTO `sys_function` VALUES ('108', '2031', '固定资产', '@asset', '');
INSERT INTO `sys_function` VALUES ('109', '203103', '参数设置', 'asset/config', '');
INSERT INTO `sys_function` VALUES ('110', '203105', '固定资产管理', 'asset/manage', '');
INSERT INTO `sys_function` VALUES ('112', '203120', '固定资产查询', 'asset/query', '');
INSERT INTO `sys_function` VALUES ('113', 'z080', '系统参数设置', 'system/security', '');
INSERT INTO `sys_function` VALUES ('114', '202009', '工作计划类型设置', 'work_plan/type', '');
INSERT INTO `sys_function` VALUES ('115', '3020', '图片浏览', 'picture', '');
INSERT INTO `sys_function` VALUES ('116', 'z01030', '图片浏览设置', 'system/picture', '');
INSERT INTO `sys_function` VALUES ('118', '205515', '调度人员管理', 'vehicle/operator', '');
INSERT INTO `sys_function` VALUES ('119', '2014', '投票管理', 'vote/manage', '');
INSERT INTO `sys_function` VALUES ('120', '502225', '人事分析', 'hr/manage/staff_analysis', '');
INSERT INTO `sys_function` VALUES ('121', 'z045', '系统代码设置', 'system/code', '');
INSERT INTO `sys_function` VALUES ('122', '5009', '绩效考核', '@score', '');
INSERT INTO `sys_function` VALUES ('123', '500901', '考核项目设定', 'score/group', '');
INSERT INTO `sys_function` VALUES ('124', '500903', '考核任务管理', 'score/flow', '');
INSERT INTO `sys_function` VALUES ('125', '500905', '进行考核', 'score/submit', '');
INSERT INTO `sys_function` VALUES ('126', '2025', '办公用品管理', '@office_Product', '');
INSERT INTO `sys_function` VALUES ('127', '202503', '办公用品信息管理', 'office_Product/Product', '');
INSERT INTO `sys_function` VALUES ('128', '202506', '办公用品登记管理', 'office_Product/manage', '');
INSERT INTO `sys_function` VALUES ('129', '501109', '部门工资上报', 'hr/salary/report', '');
INSERT INTO `sys_function` VALUES ('130', '1010', '新建工作', 'workflow/new', '');
INSERT INTO `sys_function` VALUES ('131', '1030', '工作查询', 'workflow/query', '');
INSERT INTO `sys_function` VALUES ('132', '1040', '工作监控', 'workflow/manage', '');
INSERT INTO `sys_function` VALUES ('133', '4080', '门户管理', 'system/portal/setting', '');
INSERT INTO `sys_function` VALUES ('134', 'z006', '工作流设置', '@system', '');
INSERT INTO `sys_function` VALUES ('135', 'z00620', '设计流程', 'system/workflow/flow_guide', '');
INSERT INTO `sys_function` VALUES ('136', 'z00630', '分类设置', 'system/workflow/flow_sort', '');
INSERT INTO `sys_function` VALUES ('137', '205010', '管理员设置', 'meeting/operator', '');
INSERT INTO `sys_function` VALUES ('138', '205020', '会议纪要', 'meeting/summary', '');
INSERT INTO `sys_function` VALUES ('146', 'z00813', '工作日志设置', 'system/diary', '');
INSERT INTO `sys_function` VALUES ('147', '0117', '新闻', 'news/show', '');
INSERT INTO `sys_function` VALUES ('148', '0118', '投票', 'vote/show', '');
INSERT INTO `sys_function` VALUES ('149', 'z050', '自定义字段设置', 'system/field', '');
INSERT INTO `sys_function` VALUES ('150', '2040', '资源申请与管理', '@source', '');
INSERT INTO `sys_function` VALUES ('151', 'z01210', '短信提醒设置', 'system/remind', '');
INSERT INTO `sys_function` VALUES ('152', '205507', '部门审批管理', 'vehicle/dept_manage', '');
INSERT INTO `sys_function` VALUES ('153', '203608', '借还书管理', 'book/borrow_manage', '');
INSERT INTO `sys_function` VALUES ('178', 'z035', '状态栏设置', 'system/status_text', '');
INSERT INTO `sys_function` VALUES ('179', '202501', '办公用品信息查询', 'office_Product/query', '');
INSERT INTO `sys_function` VALUES ('182', '1050', '工作委托', 'workflow/rule', '');
INSERT INTO `sys_function` VALUES ('183', '1060', '工作销毁', 'workflow/destroy', '');
INSERT INTO `sys_function` VALUES ('185', '3030', 'OA知道', 'zhidao', '');
INSERT INTO `sys_function` VALUES ('186', '9025', '项目查询', 'project/proj', '');
INSERT INTO `sys_function` VALUES ('187', '9020', '我的任务', 'project/task', '');
INSERT INTO `sys_function` VALUES ('188', '9030', '项目审批', 'project/approve', '');
INSERT INTO `sys_function` VALUES ('189', '9040', '项目文档', 'project/file', '');
INSERT INTO `sys_function` VALUES ('190', '9050', '项目问题', 'project/bug', '');
INSERT INTO `sys_function` VALUES ('191', '9060', '基础数据设置', '@project', '');
INSERT INTO `sys_function` VALUES ('192', '906010', '项目权限设置', 'project/setting/priv', '');
INSERT INTO `sys_function` VALUES ('193', '906020', '项目代码设置', 'project/setting/code', '');
INSERT INTO `sys_function` VALUES ('194', '1070', '流程日志查询', 'workflow/logs', '');
INSERT INTO `sys_function` VALUES ('196', '2008', '公告通知审批', 'notify/auditing', '');
INSERT INTO `sys_function` VALUES ('197', 'z00830', '公告通知设置', 'system/notify', '');
INSERT INTO `sys_function` VALUES ('198', 'z085', '系统接口设置', 'system/ext_user', '');
INSERT INTO `sys_function` VALUES ('199', '202507', '个人办公用品登记', 'office_Product/personal', '');
INSERT INTO `sys_function` VALUES ('200', '7010', '卷库管理', 'roll_manage/roll_room', '');
INSERT INTO `sys_function` VALUES ('201', '7030', '文件管理', 'roll_manage/roll_file', '');
INSERT INTO `sys_function` VALUES ('202', '7020', '案卷管理', 'roll_manage', '');
INSERT INTO `sys_function` VALUES ('203', '7040', '案卷借阅', '@roll_manage', '');
INSERT INTO `sys_function` VALUES ('204', '704010', '案卷借阅', 'roll_manage/roll_lend', '');
INSERT INTO `sys_function` VALUES ('205', '704020', '借阅审批', 'roll_manage/roll_lend/confirm.php', '');
INSERT INTO `sys_function` VALUES ('206', '7050', '档案统计', '@roll_manage', '');
INSERT INTO `sys_function` VALUES ('207', '705010', '借阅统计', 'roll_manage/roll_statistic/lend.php', '');
INSERT INTO `sys_function` VALUES ('208', '705020', '案卷统计', 'roll_manage/roll_statistic/roll.php', '');
INSERT INTO `sys_function` VALUES ('209', '7060', '档案销毁', 'roll_manage/destory', '');
INSERT INTO `sys_function` VALUES ('217', '203610', '设置管理员', 'book/set_manager', '');
INSERT INTO `sys_function` VALUES ('218', 'z01280', '词语过滤管理', 'system/censor_words', '');
INSERT INTO `sys_function` VALUES ('219', 'z01282', '信息过滤审核', 'system/censor_check', '');
INSERT INTO `sys_function` VALUES ('221', '906030', '项目模板管理', 'project/setting/template', '');
INSERT INTO `sys_function` VALUES ('222', '205025', '会议室设备管理', 'meeting/equipment', '');
INSERT INTO `sys_function` VALUES ('223', 'z015', '印章管理', 'system/seal_manage', '');
INSERT INTO `sys_function` VALUES ('224', '5015', '人力资源设置', '@hr', '');
INSERT INTO `sys_function` VALUES ('225', 'z020', '定时任务管理', 'system/task', '');
INSERT INTO `sys_function` VALUES ('226', 'z00640', '参数设置', 'system/workflow/config', '');
INSERT INTO `sys_function` VALUES ('227', 'y040', '即时通讯', 'im/show', '');
INSERT INTO `sys_function` VALUES ('228', 'z00840', '模板管理', 'system/model', '');
INSERT INTO `sys_function` VALUES ('229', '1045', '超时统计分析', 'workflow/timeout_stat', '');
INSERT INTO `sys_function` VALUES ('230', '501605', '题库管理', 'exam_manage/set_manage', '');
INSERT INTO `sys_function` VALUES ('231', '501610', '试题管理', 'exam_manage/quiz_manage/', '');
INSERT INTO `sys_function` VALUES ('232', '501615', '试卷管理', 'exam_manage/paper_manage/', '');
INSERT INTO `sys_function` VALUES ('233', '501620', '考试信息管理', 'exam_manage/info_pub/', '');
INSERT INTO `sys_function` VALUES ('234', '501625', '参加考试', 'exam_manage/exam_online', '');
INSERT INTO `sys_function` VALUES ('235', '3040', '维基百科', 'wiki', '');
INSERT INTO `sys_function` VALUES ('236', 'z025', '紧急通知设置', 'system/urgent_notify', '');
INSERT INTO `sys_function` VALUES ('237', '205518', '油耗统计', 'vehicle/oil_cost', '');
INSERT INTO `sys_function` VALUES ('238', '202508', '办公用品库设置', 'office_Product/office_type', '');
INSERT INTO `sys_function` VALUES ('239', '204001', '资源申请与管理', 'source/manage', '');
INSERT INTO `sys_function` VALUES ('240', '204002', '周期性资源安排', 'source/cyclesource', '');
INSERT INTO `sys_function` VALUES ('251', '202510', '办公用品报表', 'office_Product/report', '');
INSERT INTO `sys_function` VALUES ('252', '5016', '在线考试', '@exam_manage', '');
INSERT INTO `sys_function` VALUES ('253', 'z00650', '业务引擎设置', 'system/workflow/flow_hook', '');
INSERT INTO `sys_function` VALUES ('254', 'z00660', '报表设置', 'system/workflow/flow_report', '');
INSERT INTO `sys_function` VALUES ('255', 'z00670', '数据源管理', 'system/workflow/flow_data', '');
INSERT INTO `sys_function` VALUES ('256', '1041', '数据报表', 'workflow/report', '');
INSERT INTO `sys_function` VALUES ('257', '4090', '门户内容管理', 'system/portal/content', '');
INSERT INTO `sys_function` VALUES ('258', 'z010', '知识管理设置', '@system', '');
INSERT INTO `sys_function` VALUES ('461', '6501', '发文管理', '@document', '');
INSERT INTO `sys_function` VALUES ('462', '650101', '发文拟稿', 'document/index.php/send/draft', '');
INSERT INTO `sys_function` VALUES ('463', '650105', '发文核稿', 'document/index.php/send/approve', '');
INSERT INTO `sys_function` VALUES ('464', '650110', '套红盖章', 'document/index.php/send/seal', '');
INSERT INTO `sys_function` VALUES ('465', '650115', '发文列表', 'document/index.php/send/sendlist', '');
INSERT INTO `sys_function` VALUES ('466', '6505', '收文管理', '@document', '');
INSERT INTO `sys_function` VALUES ('467', '650501', '收文登记', 'document/index.php/recv/register', '');
INSERT INTO `sys_function` VALUES ('468', '650505', '领导批阅', 'document/index.php/recv/approve', '');
INSERT INTO `sys_function` VALUES ('469', '650510', '收文分发', 'document/index.php/recv/outgiving', '');
INSERT INTO `sys_function` VALUES ('470', '650515', '收文阅读', 'document/index.php/recv/read', '');
INSERT INTO `sys_function` VALUES ('471', '6510', '基础设置', '@document_setting', '');
INSERT INTO `sys_function` VALUES ('472', '651001', '参数设置', 'document/index.php/setting/config', '');
INSERT INTO `sys_function` VALUES ('473', '651005', '主题词管理', 'document/index.php/setting/keywords', '');
INSERT INTO `sys_function` VALUES ('474', '651010', '公文类型设置', 'document/index.php/setting/type', '');
INSERT INTO `sys_function` VALUES ('475', '651020', '收文权限设置', 'document/index.php/setting/priv', '');
INSERT INTO `sys_function` VALUES ('481', '502203', '合同管理', 'hr/manage/staff_contract', '');
INSERT INTO `sys_function` VALUES ('482', '502205', '奖惩管理', 'hr/manage/staff_incentive', '');
INSERT INTO `sys_function` VALUES ('483', '502207', '证照管理', 'hr/manage/staff_license', '');
INSERT INTO `sys_function` VALUES ('484', '502209', '学习经历', 'hr/manage/staff_learn_experience', '');
INSERT INTO `sys_function` VALUES ('485', '502211', '工作经历', 'hr/manage/staff_work_experience', '');
INSERT INTO `sys_function` VALUES ('486', '502213', '劳动技能', 'hr/manage/staff_labor_skills', '');
INSERT INTO `sys_function` VALUES ('487', '502215', '社会关系', 'hr/manage/staff_relatives', '');
INSERT INTO `sys_function` VALUES ('488', '502217', '人事调动', 'hr/manage/staff_transfer', '');
INSERT INTO `sys_function` VALUES ('489', '502219', '离职管理', 'hr/manage/staff_leave', '');
INSERT INTO `sys_function` VALUES ('490', '502221', '复职管理', 'hr/manage/staff_reinstatement', '');
INSERT INTO `sys_function` VALUES ('491', '502222', '职称评定', 'hr/manage/staff_title_evaluation', '');
INSERT INTO `sys_function` VALUES ('492', '502223', '员工关怀', 'hr/manage/staff_care', '');
INSERT INTO `sys_function` VALUES ('494', '5023', '招聘管理', '@hr', '');
INSERT INTO `sys_function` VALUES ('495', '502301', '招聘需求', 'hr/recruit/requirements', '');
INSERT INTO `sys_function` VALUES ('496', '502303', '招聘计划', 'hr/recruit/plan', '');
INSERT INTO `sys_function` VALUES ('497', '502305', '招聘计划审批', 'hr/recruit/plan_approval', '');
INSERT INTO `sys_function` VALUES ('498', '502307', '人才库', 'hr/recruit/hr_pool', '');
INSERT INTO `sys_function` VALUES ('499', '502309', '招聘筛选', 'hr/recruit/filter', '');
INSERT INTO `sys_function` VALUES ('500', '502311', '招聘录用', 'hr/recruit/recruitment', '');
INSERT INTO `sys_function` VALUES ('501', '502313', '人才分析', 'hr/recruit/analysis', '');
INSERT INTO `sys_function` VALUES ('502', '5005', '培训管理', '@hr', '');
INSERT INTO `sys_function` VALUES ('503', '500501', '培训计划', 'hr/training/plan', '');
INSERT INTO `sys_function` VALUES ('504', '500505', '培训记录', 'hr/training/record', '');
INSERT INTO `sys_function` VALUES ('505', '500503', '培训计划审批', 'hr/training/approval/', '');
INSERT INTO `sys_function` VALUES ('506', '500701', '考勤审批', 'attendance/manage/confirm/', '');
INSERT INTO `sys_function` VALUES ('507', '500703', '考勤记录', 'attendance/manage/user_manage', '');
INSERT INTO `sys_function` VALUES ('508', '500705', '考勤统计', 'attendance/manage/query', '');
INSERT INTO `sys_function` VALUES ('509', '501103', '薪酬基数设置', 'hr/salary/staff_insurance', '');
INSERT INTO `sys_function` VALUES ('510', '501111', '福利管理', 'hr/salary/welfare_manage', '');
INSERT INTO `sys_function` VALUES ('511', '5013', '员工自助查询', 'hr/self_find', '');
INSERT INTO `sys_function` VALUES ('512', '501503', '人力资源管理员', 'hr/setting/hr_manager', '');
INSERT INTO `sys_function` VALUES ('513', '501505', 'HRMS代码设置', 'hr/setting/hr_code', '');
INSERT INTO `sys_function` VALUES ('514', '501101', '薪酬项目及保险设置', 'hr/salary/insurance_para', '');
INSERT INTO `sys_function` VALUES ('515', '500707', '值班排班管理', 'attendance/manage/on_duty', '');
INSERT INTO `sys_function` VALUES ('532', 'b050', '专业视频会议', 'gbtmeet', '');
INSERT INTO `sys_function` VALUES ('533', 'z070', '附件管理', 'system/attachment', '');
INSERT INTO `sys_function` VALUES ('534', 'z01224', '即时通讯管理', 'system/im', '');
INSERT INTO `sys_function` VALUES ('535', '3050', '文档检索中心', 'index', '');
INSERT INTO `sys_function` VALUES ('536', 'z00680', '管理日志', 'system/workflow/flow_log', '');
INSERT INTO `sys_function` VALUES ('537', '500709', '查岗质询登记', 'attendance/manage/ask_duty', '');
INSERT INTO `sys_function` VALUES ('538', 'z01205', '电子邮件设置', 'system/email', '');
INSERT INTO `sys_function` VALUES ('539', '202511', '办公用品发放', 'office_Product/grant', '');
INSERT INTO `sys_function` VALUES ('540', 'z090', '服务器监控', 'system/monitor', '');
INSERT INTO `sys_function` VALUES ('548', 'e001', '平台设置', '@ext_data', '');
INSERT INTO `sys_function` VALUES ('549', 'e005', '信息接收与发布', '@ext_data', '');
INSERT INTO `sys_function` VALUES ('550', 'a001', '报表管理', 'reportshop/workshop', '');
INSERT INTO `sys_function` VALUES ('551', 'a002', '模板管理', '@setreppara', '');
INSERT INTO `sys_function` VALUES ('552', 'a00201', '设计模板', 'reportshop/design/report', '');
INSERT INTO `sys_function` VALUES ('553', 'a00202', '模板分类', 'reportshop/console/repkind', '');
INSERT INTO `sys_function` VALUES ('554', 'a00203', '基础代码', 'reportshop/console/code', '');
INSERT INTO `sys_function` VALUES ('555', 'a00204', '自动编号', 'reportshop/console/autocode', '');
INSERT INTO `sys_function` VALUES ('556', 'a00205', '数 据 源', 'reportshop/console/database', '');
INSERT INTO `sys_function` VALUES ('557', 'a00206', '系统工具', 'reportshop/system/exchange', '');
INSERT INTO `sys_function` VALUES ('558', 'a00207', '注册信息', 'reportshop/system/reg_view', '');
INSERT INTO `sys_function` VALUES ('600', 'e00520', '信息发布', 'ext_data/info/send', '');
INSERT INTO `sys_function` VALUES ('601', 'e00510', '信息接收', 'ext_data/info/recv', '');
INSERT INTO `sys_function` VALUES ('602', 'e010', '工作接收与处理', '@ext_data', '');
INSERT INTO `sys_function` VALUES ('603', 'e01010', '待办工作', 'ext_data/workflow/my', '');
INSERT INTO `sys_function` VALUES ('604', 'e01020', '权限与规则设置', 'ext_data/workflow/rule', '');
INSERT INTO `sys_function` VALUES ('605', 'z00420', '外部机构管理', 'system/ext_dept', '');
INSERT INTO `sys_function` VALUES ('606', '906005', '项目自定义设置', 'project/setting/cust/sys', '');
INSERT INTO `sys_function` VALUES ('607', '202505', '办公用品部门审批', 'office_Product/dept_approval', '');
INSERT INTO `sys_function` VALUES ('609', 'z00809', '日程安排设置', 'system/calendar', '');
INSERT INTO `sys_function` VALUES ('626', 'z093', '三员安全管理', 'system/secure_rule', '');
INSERT INTO `sys_function` VALUES ('628', '500904', '被考核人自评', 'score/self_assessment', '');
INSERT INTO `sys_function` VALUES ('629', '501616', '主观题阅卷', 'exam_manage/subject_score/', '');
INSERT INTO `sys_function` VALUES ('630', '5010', '积分管理', '@hr', '');
INSERT INTO `sys_function` VALUES ('631', '501001', '积分录入', 'hr/integral/input', '');
INSERT INTO `sys_function` VALUES ('632', '501002', '积分查询', 'hr/integral/query', '');
INSERT INTO `sys_function` VALUES ('633', '501003', '积分项设置', 'hr/integral/item_setting', '');
INSERT INTO `sys_function` VALUES ('634', '0115', '智协同', 'itask', '');
INSERT INTO `sys_function` VALUES ('635', 'z094', '安全员管理', 'system/secure_safer', '');
INSERT INTO `sys_function` VALUES ('636', 'z095', '审计员管理', 'system/secure_logs', '');
INSERT INTO `sys_function` VALUES ('637', '1080', '数据归档', 'workflow/archive', '');
INSERT INTO `sys_function` VALUES ('638', 'z097', 'ERP数据源配置', 'system/to_erp/data_source', '');
INSERT INTO `sys_function` VALUES ('639', 'z016', '手机签章管理', 'system/mobile_seal', '');
INSERT INTO `sys_function` VALUES ('640', 'e00101', '参数设置', 'ext_data/admin/setting', '');
INSERT INTO `sys_function` VALUES ('641', 'e00102', '流程模型同步', 'ext_data/admin/model', '');
INSERT INTO `sys_function` VALUES ('642', 'e00103', '交换历史记录', 'ext_data/admin/logs', '');
INSERT INTO `sys_function` VALUES ('643', '0107', '邮件审批', 'email/audit/', '');
INSERT INTO `sys_function` VALUES ('644', '0109', '邮件审批日志', 'email/audit_log/', '');
INSERT INTO `sys_function` VALUES ('1001', '5002', '新版模块', '@hr', '');
INSERT INTO `sys_function` VALUES ('1002', '500223', '入职登记表', 'hr/manage/enter', '');
INSERT INTO `sys_function` VALUES ('1003', '500232', '人事档案查询', 'hr/manage/personnel', '');
INSERT INTO `sys_function` VALUES ('1004', '500224', '人事异动申请流程', 'hr/manage/transaction', '');
INSERT INTO `sys_function` VALUES ('1005', '500225', '人事异动审核', 'hr/manage/transaction_approval', '');
INSERT INTO `sys_function` VALUES ('1006', '500227', '离职申请', 'hr/manage/Quit', '');
INSERT INTO `sys_function` VALUES ('1007', '500228', '离职申请单审核', 'hr/manage/Quit_approval', '');
INSERT INTO `sys_function` VALUES ('1008', '500221', '面试记录表', 'hr/manage/Interview', '');
INSERT INTO `sys_function` VALUES ('1009', '500222', '面试记录表审批', 'hr/manage/Interview_approval', '');
INSERT INTO `sys_function` VALUES ('1010', '500231', '薪资查询', 'hr/manage/salary', '');
INSERT INTO `sys_function` VALUES ('1011', '500229', '交接清单上传', 'hr/manage/Detailed', '');
INSERT INTO `sys_function` VALUES ('1012', '500230', '交接清单确认', 'hr/manage/Detailed_approval', '');
INSERT INTO `sys_function` VALUES ('1013', '5003', '工作能力(季度)考核', '@hr', '');
INSERT INTO `sys_function` VALUES ('1014', '5004', '工作业绩(月度)考核', '@hr', '');
INSERT INTO `sys_function` VALUES ('1015', '500301', '考核模板', 'hr/kpi/kpimb', '');
INSERT INTO `sys_function` VALUES ('1016', '500302', '模板关联', 'hr/kpi/kpigl', '');
INSERT INTO `sys_function` VALUES ('1017', '500303', '考核记录', 'hr/kpi/kpikh', '');
INSERT INTO `sys_function` VALUES ('1018', '500304', '考核审批', 'hr/kpi/kpisp', '');
INSERT INTO `sys_function` VALUES ('1019', '500401', 'KPI模板', 'hr/kpikh/kpimb', '');
INSERT INTO `sys_function` VALUES ('1020', '500402', 'KPI关联', 'hr/kpikh/kpigl', '');
INSERT INTO `sys_function` VALUES ('1021', '500403', 'KPI考核', 'hr/kpikh/kpikh', '');
INSERT INTO `sys_function` VALUES ('1022', '500404', 'KPI审批', 'hr/kpikh/kpisp', '');
INSERT INTO `sys_function` VALUES ('1023', '500405', 'KPI汇总统计', 'hr/kpikh/kpihz', '');
INSERT INTO `sys_function` VALUES ('1024', '500406', '公共指标考核', 'hr/kpikh/publickh/', '');
INSERT INTO `sys_function` VALUES ('1025', '500408', '销售业绩考核', 'hr/kpikh/salesPerformance/', '');
INSERT INTO `sys_function` VALUES ('1026', '500299', '案例模板', 'hr/demo/demo_one', '');
INSERT INTO `sys_function` VALUES ('1027', '500226', '奖惩申请单', 'hr/manage/reward_punishment', '');
INSERT INTO `sys_function` VALUES ('1028', '500233', '合同登记表', 'hr/form_manage/contract_registration', '');
INSERT INTO `sys_function` VALUES ('1029', '0103', '内部邮箱', 'mail/my', '');
INSERT INTO `sys_function` VALUES ('1030', '500201', '人事系统参数管理', 'hr/form_manage/param_manage', '');
INSERT INTO `sys_function` VALUES ('1031', '500202', '项目比例管理', 'hr/pm_manage/', '');
INSERT INTO `sys_function` VALUES ('1032', '500203', '数据字典管理', 'hr/form_manage/data_dictionary', '');
INSERT INTO `sys_function` VALUES ('1033', '500220', '普工面试记录表', 'hr/manage/Interview/general_worker_flow', '');
INSERT INTO `sys_function` VALUES ('1034', 'c001', 'CRM外部系统', 'customer_relationship/manage', '');
INSERT INTO `sys_function` VALUES ('1035', '5501', '名词对照库', 'control_library/', '');
INSERT INTO `sys_function` VALUES ('1036', 'c002', '客户信息管理', 'customer_relationship/customer_data', '');
INSERT INTO `sys_function` VALUES ('1037', 'c003', '立项申请', 'customer_relationship/project_review', '');
INSERT INTO `sys_function` VALUES ('1038', 'c004', '销售合同评审', 'customer_relationship/sales_contract_review', '');
INSERT INTO `sys_function` VALUES ('1039', 'c005', '生产通知单', 'customer_relationship/production_order', '');
INSERT INTO `sys_function` VALUES ('1040', 'c006', '发货通知单', 'customer_relationship/shipping_notice', '');
INSERT INTO `sys_function` VALUES ('1041', 'c007', '项目参与人登记', 'customer_relationship/project_participant', '');
INSERT INTO `sys_function` VALUES ('1042', 'c008', '合作协议登记表', 'customer_relationship/protocol_archive/index1.php', '');
INSERT INTO `sys_function` VALUES ('1043', 'c009', '销售合同登记表', 'customer_relationship/protocol_archive/index2.php', '');
INSERT INTO `sys_function` VALUES ('1044', 'c010', '保函登记表', 'customer_relationship/protocol_archive/index3.php', '');
INSERT INTO `sys_function` VALUES ('1045', 'd001', '标准数据表格', 'demo/index.php', '');
INSERT INTO `sys_function` VALUES ('1046', 'c011', '授权函登记表', 'customer_relationship/protocol_archive/index4.php', '');
